version: '3.9'

services:
    vault: ## todo how to launch vault and vault-cache with 2 different container names
        build: .
        container_name: ${EXEC_TYPE}
        env_file:
            - ./env/mongo.env
            - ${VAULT_ENV_FILE}
        expose:
            - ${VAULT_PORT}
        networks:
            - maestro:vault
        restart: on-failure

networks:
    maestro:vault:
        external: true

## todo mongo
## todo choose between mongo.env and putting mongo variables into vault.env