version: '3.9'

services:
    vault: ## todo how to launch vault and vault-cache with 2 different container names
        build:
            dockerfile: Dockerfile
        container_name: vault
        environment:
            MONGO_URI: ${MONGO_URI}
            VAULT_ADDRESS: ${VAULT_ADDRESS}
            VAULT_PORT: ${VAULT_PORT}
            EXEC_TYPE: ${EXEC_TYPE}

        expose:
            - ${VAULT_PORT}
        networks:
            - maestro:vault
        restart: on-failure

networks:
    maestro:vault:
        external: true

## todo mongo
## todo choose between mongo.env and putting mongo variables into vault.env